services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    platform: linux/arm64/v8  # Specific for M2 Mac
    container_name: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    platform: linux/arm64/v8  # Specific for M2 Mac
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - "8081:8081"
    networks:
      - mongo_network
    depends_on:
      mongodb:
        condition: service_healthy

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 